version: "3"

services:
  detox-tests:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    privileged: true # Necessário para acesso ao ADB
    volumes:
      - .:/app
    working_dir: /app
    command: >
      sh -c '
      npm install &&
      npm start &
      sleep 1 &&
      detox build -c android.emu.debug &&
      detox test -c android.emu.debug --headless --gpu swiftshader_indirect --take-screenshots all --record-videos all -l trace
      '
